### ISSUE TITLE
ImportError: cannot import name 'OmegleClient' from 'pyomegle' (C:\Users\----\AppData\Roaming\Python\Python37\site-packages\pyomegle\__init__.py)

### ISSUE THREAD

**Issue by HRRZMDev** [elias94/pyomegle#11]
Im using python 3 as I heard that it is now supported due to Mechanise now supporting python 3. The issue also occurs with OmegleHandler. Previously, the issue could be fixed by using IDLE as my editor but after reinstalling python (for other reasons) this fix no longer works.

**Comment by eliascotto** [comment]
The library as been updated to use the latest version of Mechanise just recently so is now compatible with Python3. Try again and open a new issue if it doesn't work.
