### ISSUE TITLE
Unhandled event: ['error', 'Please reload Omegle to continue.']

### ISSUE THREAD

**Issue by Threadz112** [elias94/pyomegle#19]
When starting the script i get this error, never got this error before. always worked today it started this error.

Unhandled event: ['error', 'Please reload Omegle to continue.']

I heard it was due to Omegles update today about clicking the ToS. I am not very good at coding python yet and would like help if possible thanks!

**Comment by Threadz112** [comment]
@elias94

**Comment by eliascotto** [comment]
Hey @Threadz112 I'm not using the library and there is no active maintainers at the moment.
The code is not difficult, you can give it a try and open a pull request and maybe someone can review your code :)

**Comment by isaackogan** [comment]
If it helps, I can basically guarantee it's to do with the new user agreement buttons they added.

**Comment by isaackogan** [comment]
Honestly. I might as well maintain this lol. Creating a pull request with the fix.

**Comment by isaackogan** [comment]
Edit: Since you aren't planning on maintaining this anymore I'm just going to re-code the lib on my own based off yours so I can have full access. I'll edit the link in for that when it's finished, and be sure to give full credit to you.

**Comment by isaackogan** [comment]
https://github.com/isaackogan/OmeglePy

**Comment by oketariq** [comment]
late to the issue but for anyone still having problems with this
use this repo it has it fixed https://github.com/onsagere/pyomegle

**Comment by eliascotto** [comment]
thanks hdboye. If you want you can open a PR and I will have a look to merge and update the dependency

**Comment by argonzalez2016** [comment]
> late to the issue but for anyone still having problems with this use this repo it has it fixed https://github.com/onsagere/pyomegle

This repo isn't working for me.
