### ISSUE TITLE
What does this code do?

### ISSUE THREAD

**Issue by m1zoo** [elias94/pyomegle#8]
`while 1:
while True:
    input_str = raw_input('')           # string input

    if input_str.strip() == '/next':
        c.next()                        # new conversation
    elif input_str.strip() == '/exit':
        c.disconnect()                  # disconnect chat session
        break
    else:
        c.send(input_str)        `

I know there's comments, and I know I'm retarded. But what does it do exactly? Where do you put /next and /exit? Input for the bot or for you? What's the difference between c.send() and omegle.send()?

**Comment by eliascotto** [comment]
If you type `/next` into the input go into a next conversation, if you type `/exit` disconnect from the current session and close the program.
